from __future__ import annotations

from pathlib import Path


def require_file(path: str | Path) -> None:
	path = Path(path)
	if not path.is_file():
		raise FileNotFoundError(f"File not found: {path}")


def validate_ttl(ttl_path: str | Path) -> None:
	require_file(ttl_path)
	content = Path(ttl_path).read_text(encoding="utf-8", errors="ignore")
	if "@prefix" not in content:
		raise ValueError("TTL validation failed: missing @prefix declarations")
	if "." not in content:
		raise ValueError("TTL validation failed: no triple terminators found ('.')")


def validate_csv_header(csv_path: str | Path) -> None:
	require_file(csv_path)
	expected = (
		"ParticipantID,HandSize_cm,TaskID,ToolSet,Time_s,NumOperations,ErrorRate_pct,"
		"SwitchCount,SwitchTime_s,PerceivedCognitiveCost,PerceivedDiscomfort"
	)
	first = Path(csv_path).read_text(encoding="utf-8", errors="ignore").splitlines()[0].strip()
	if first != expected:
		raise ValueError(f"CSV validation failed: header mismatch.\nExpected: {expected}\nActual:   {first}")


def validate_puml(puml_path: str | Path) -> None:
	require_file(puml_path)
	content = Path(puml_path).read_text(encoding="utf-8", errors="ignore")
	if "@startuml" not in content or "@enduml" not in content:
		raise ValueError("PUML validation failed: missing @startuml/@enduml")


def validate_mermaid(mmd_path: str | Path) -> None:
	require_file(mmd_path)
	first = Path(mmd_path).read_text(encoding="utf-8", errors="ignore").splitlines()[0]
	if not (first.startswith("flowchart") or first.startswith("graph")):
		raise ValueError("Mermaid validation failed: expected 'flowchart' or 'graph' on first line")


def validate_dot(dot_path: str | Path) -> None:
	require_file(dot_path)
	first = Path(dot_path).read_text(encoding="utf-8", errors="ignore")
	if "digraph" not in first:
		raise ValueError("DOT validation failed: missing 'digraph' keyword")


def validate_shapes(shapes_path: str | Path | None) -> None:
	if not shapes_path:
		return
	require_file(shapes_path)
	content = Path(shapes_path).read_text(encoding="utf-8", errors="ignore")
	if "@prefix sh:" not in content and "http://www.w3.org/ns/shacl#" not in content:
		raise ValueError("SHACL validation failed: missing sh: prefix or SHACL namespace")


def generate_dictionary(csv_path: str | Path, out_path: str | Path) -> None:
	require_file(csv_path)
	header = Path(csv_path).read_text(encoding="utf-8", errors="ignore").splitlines()[0].strip()
	columns = header.split(",")
	lines = ["# Spoon Diversity Data Dictionary (v0.3)", "", "Generated by spoon-diversity CLI.", "", "## Columns"]
	mappings = {
		"ParticipantID": ("string", "", "schema:identifier (sp:Participant)"),
		"HandSize_cm": ("decimal >= 0", "cm", "sp:handSizeCm"),
		"TaskID": ("string", "", "sp:Task (identifier)"),
		"ToolSet": ("string", "", "sp:ToolSet (identifier)"),
		"Time_s": ("decimal >= 0", "s", "sp:timeSeconds"),
		"NumOperations": ("integer >= 0", "count", "sp:numOperations"),
		"ErrorRate_pct": ("decimal 0–100", "%", "sp:errorRatePercent"),
		"SwitchCount": ("integer >= 0", "count", "sp:switchCount"),
		"SwitchTime_s": ("decimal >= 0", "s", "sp:switchTimeSeconds"),
		"PerceivedCognitiveCost": ("integer 1–7", "Likert", "sp:perceivedCognitiveCost"),
		"PerceivedDiscomfort": ("integer 1–7", "Likert", "sp:perceivedDiscomfort"),
	}
	for col in columns:
		type_str, unit, mapping = mappings.get(col, ("string", "", ""))
		lines.append(f"### {col}\n- Type: {type_str}\n- Unit: {unit}\n- Mapping: {mapping}\n")
	lines.append("## Missing-Value Policy")
	lines.append("- Use empty cells for missing numeric values; do not use NaN.")
	lines.append("- Use 'NA' for categorical unknowns where applicable.")
	Path(out_path).write_text("\n".join(lines), encoding="utf-8")


